name: deploy_to_digitalocean

services:
  - name: web
    environment_slug: python
    github:
      repo: github.com/johndiginee/deploy_to_digitalocean  # Replace with your GitHub repo
      branch: master  # Replace with your desired branch
    routes:
      - path: /


envs:
  - key: DJANGO_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: your_secret_key_here  # Replace with your Django app's secret key
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "False"  # Set to "True" for development and "False" for production
  - key: DJANGO_DB_ENGINE
    scope: RUN_AND_BUILD_TIME
    value: django.db.backends.sqlite3
  - key: DJANGO_DB_NAME
    scope: RUN_AND_BUILD_TIME
    value: /deploy/db.sqlite3  # Set the path to your SQLite database file

jobs:
  - name: Collect Static Files
    run_command: python manage.py collectstatic --noinput

  - name: Apply Migrations
    run_command: python manage.py migrate

  - name: Start Gunicorn
    run_command: gunicorn --worker-tmp-dir /dev/shm deploy.wsgi  # Replace 'deploy' with your project's name

  # Additional setup commands can be added here if needed.
